#pragma once

enum syscall_id_t {
    SYS_EXIT   = 0,
    SYS_THEXIT = 1,
    SYS_USLEEP = 2,
    SYS_YIELD  = 3,

    SYS_OPEN    = 4,
    SYS_READ    = 5,
    SYS_WRITE   = 6,
    SYS_CLOSE   = 7,
    SYS_FSTAT   = 8,
    SYS_SEEK    = 9,
    SYS_IOCTL   = 10,
    SYS_ISATTY  = 11,
    SYS_DUP     = 12,
    SYS_DUP2    = 13,
    SYS_PIPE    = 14,
    SYS_CHDIR   = 15,
    SYS_GETCWD  = 16,
    SYS_ACCESS  = 17,
    SYS_STATAT  = 18,
    SYS_MMAP    = 19,
    SYS_MUNMAP  = 20,
    SYS_CHMOD   = 21,
    SYS_FCHMOD  = 22,
    SYS_MKDIR   = 23,
    SYS_MKFIFO  = 24,
    SYS_MKNOD   = 25,
    SYS_UMASK   = 26,
    SYS_READDIR = 27,
    SYS_SEEKDIR = 28,
    SYS_TELLDIR = 29,
    SYS_FCNTL   = 30,
    SYS_CREAT   = 31,
    SYS_MOUNT   = 32,
    SYS_UMOUNT  = 33,
    SYS_UNLINK  = 34,

    SYS_FORK   = 44,
    SYS_EXECVE = 45,
    SYS_WAIT   = 46,
    SYS_GETPID = 47,
    SYS_GETTID = 48,
    SYS_KILL   = 49,
    SYS_SIGACT = 50,
    SYS_SIGRET = 51,
    SYS_NICE   = 52,

    SYS_TCREATE = 72,
    SYS_TJOIN   = 73,
    SYS_TABORT  = 74,
    SYS_TDETACH = 75,
    SYS_TKILL   = 76,

    SYS_GETHOSTNAME = 80,
    SYS_SETHOSTNAME = 81,
    SYS_GETENV      = 82,
    SYS_SETENV      = 83,

    SYS_GETEGID  = 90,
    SYS_GETEUID  = 91,
    SYS_GETGID   = 92,
    SYS_GETUID   = 93,
    SYS_SETEGID  = 94,
    SYS_SETEUID  = 95,
    SYS_SETGID   = 96,
    SYS_SETUID   = 97,
    SYS_SETREGID = 98,
    SYS_SETREUID = 99,

    SYS_PANIC = 250,
    SYS_TEST1 = 251,
    SYS_TEST2 = 252,
    SYS_TEST3 = 253,
    SYS_TEST4 = 254,
    SYS_TEST5 = 255,
};
