#include "aex/dev/input.hpp"
#include "aex/dev/input/keymap.hpp"

namespace AEX::Dev::Input {
    keymap default_keymap = {{
        [0]              = {},
        [1]              = {},
        [2]              = {},
        [3]              = {},
        [KEY_A]          = key::normalKey('a', 'A'),
        [KEY_B]          = key::normalKey('b', 'B'),
        [KEY_C]          = key::normalKey('c', 'C'),
        [KEY_D]          = key::normalKey('d', 'D'),
        [KEY_E]          = key::normalKey('e', 'E'),
        [KEY_F]          = key::normalKey('f', 'F'),
        [KEY_G]          = key::normalKey('g', 'G'),
        [KEY_H]          = key::normalKey('h', 'H'),
        [KEY_I]          = key::normalKey('i', 'I'),
        [KEY_J]          = key::normalKey('j', 'J'),
        [KEY_K]          = key::normalKey('k', 'K'),
        [KEY_L]          = key::normalKey('l', 'L'),
        [KEY_M]          = key::normalKey('m', 'M'),
        [KEY_N]          = key::normalKey('n', 'N'),
        [KEY_O]          = key::normalKey('o', 'O'),
        [KEY_P]          = key::normalKey('p', 'P'),
        [KEY_Q]          = key::normalKey('q', 'Q'),
        [KEY_R]          = key::normalKey('r', 'R'),
        [KEY_S]          = key::normalKey('s', 'S'),
        [KEY_T]          = key::normalKey('t', 'T'),
        [KEY_U]          = key::normalKey('u', 'U'),
        [KEY_V]          = key::normalKey('v', 'V'),
        [KEY_W]          = key::normalKey('w', 'W'),
        [KEY_X]          = key::normalKey('x', 'X'),
        [KEY_Y]          = key::normalKey('y', 'Y'),
        [KEY_Z]          = key::normalKey('z', 'Z'),
        [KEY_1]          = key::symbolKey('1', '!'),
        [KEY_2]          = key::symbolKey('2', '@'),
        [KEY_3]          = key::symbolKey('3', '#'),
        [KEY_4]          = key::symbolKey('4', '$'),
        [KEY_5]          = key::symbolKey('5', '%'),
        [KEY_6]          = key::symbolKey('6', '^'),
        [KEY_7]          = key::symbolKey('7', '&'),
        [KEY_8]          = key::symbolKey('8', '*'),
        [KEY_9]          = key::symbolKey('9', '('),
        [KEY_0]          = key::symbolKey('0', ')'),
        [KEY_RETURN]     = key::symbolKey('\r'),
        [KEY_ESCAPE]     = key::symbolKey('\x1B'),
        [KEY_BACKSPACE]  = key::symbolKey('\b'),
        [KEY_TAB]        = key::symbolKey('\t'),
        [KEY_SPACE]      = key::symbolKey(' '),
        [KEY_MINUS]      = key::symbolKey('-', '_'),
        [KEY_EQUAL]      = key::symbolKey('=', '+'),
        [KEY_LEFTBRACE]  = key::symbolKey('[', '{'),
        [KEY_RIGHTBRACE] = key::symbolKey(']', '}'),
        [KEY_BACKSLASH]  = key::symbolKey('\\', '|'),
        [KEY_BACKSLASH2] = key::symbolKey('\\', '|'),
        [KEY_SEMICOLON]  = key::symbolKey(';', ':'),
        [KEY_APOSTROPHE] = key::symbolKey('\'', '"'),
        [KEY_GRAVE]      = key::symbolKey('`', '~'),
        [KEY_COMMA]      = key::symbolKey(',', '<'),
        [KEY_DOT]        = key::symbolKey('.', '>'),
        [KEY_SLASH]      = key::symbolKey('/', '?'),
    }};
}